from typing import Any, Optional

class BasePiping:
    def __add__(self, other: Any) -> None: ...
    def __sub__(self, other: Any) -> None: ...
    def __mul__(self, other: Any) -> None: ...
    def __matmul__(self, other: Any) -> None: ...
    def __truediv__(self, other: Any) -> None: ...
    def __floordiv__(self, other: Any) -> None: ...
    def __mod__(self, other: Any) -> None: ...
    def __divmod__(self, other: Any) -> None: ...
    def __pow__(self, other: Any, modulo: Optional[Any] = ...) -> None: ...
    def __lshift__(self, other: Any) -> None: ...
    def __rshift__(self, other: Any) -> None: ...
    def __and__(self, other: Any) -> None: ...
    def __xor__(self, other: Any) -> None: ...
    def __or__(self, other: Any) -> None: ...
    def __radd__(self, other: Any) -> None: ...
    def __rsub__(self, other: Any) -> None: ...
    def __rmul__(self, other: Any) -> None: ...
    def __rmatmul__(self, other: Any) -> None: ...
    def __rtruediv__(self, other: Any) -> None: ...
    def __rfloordiv__(self, other: Any) -> None: ...
    def __rmod__(self, other: Any) -> None: ...
    def __rdivmod__(self, other: Any) -> None: ...
    def __rpow__(self, other: Any) -> None: ...
    def __rlshift__(self, other: Any) -> None: ...
    def __rrshift__(self, other: Any) -> None: ...
    def __rand__(self, other: Any) -> None: ...
    def __rxor__(self, other: Any) -> None: ...
    def __ror__(self, other: Any) -> None: ...
    def __iadd__(self, other: Any) -> None: ...
    def __isub__(self, other: Any) -> None: ...
    def __imul__(self, other: Any) -> None: ...
    def __imatmul__(self, other: Any) -> None: ...
    def __itruediv__(self, other: Any) -> None: ...
    def __ifloordiv__(self, other: Any) -> None: ...
    def __imod__(self, other: Any) -> None: ...
    def __ipow__(self, other: Any, modulo: Optional[Any] = ...) -> None: ...
    def __ilshift__(self, other: Any) -> None: ...
    def __irshift__(self, other: Any) -> None: ...
    def __iand__(self, other: Any) -> None: ...
    def __ixor__(self, other: Any) -> None: ...
    def __ior__(self, other: Any) -> None: ...
    def __neg__(self) -> None: ...
    def __pos__(self) -> None: ...
    def __abs__(self) -> None: ...
    def __invert__(self) -> None: ...
    def __int__(self): ...
    def __float__(self) -> None: ...
