from collections.abc import Iterable
from typing import Any, Callable, Collection, List, Union

def pipe(invalue: Any, *chain: List[Callable]) -> Any: ...

class PipingExperiment:
    result: Any = ...
    def __init__(self, seed: Any) -> PipingExperiment: ...
    def __or__(self, step: Callable) -> PipingExperiment: ...
P = PipingExperiment

def raises(ExcType: Exception) -> Callable: ...

IT: Any
itrt = Iterable

def empty_ob(o: Any) -> bool: ...
def func_file(func: Any): ...
def nanoast(obj: obj) -> None: ...
NarrowingPredicate = Union[Any, Callable[[Any], bool]]

class Narrowable:
    def narrow(self, pred: NarrowingPredicate) -> Narrowable: ...
    def __getitem__(self, idx: Any) -> Any: ...

def narrowable(src: Union[Any, Collection]) -> Narrowable: ...
